[build]
  command = "npm run build"
  publish = "build"

  [build.environment]
    SECRETS_SCAN_OMIT_KEYS = "REACT_APP_API_KEY,REACT_APP_APP_ID,REACT_APP_AUTH_DOMAIN,REACT_APP_MESSAGING_SENDER_ID,REACT_APP_PROJECT_ID,REACT_APP_STORAGE_BUCKET"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200